name: integration

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'dist/**'
      - 'src/**'
      - 'action.yml'
      - 'yarn.lock'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'dist/**'
      - 'src/**'
      - 'action.yml'
      - 'yarn.lock'

jobs:
  no-auth:
    name: Download w/o auth
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Show version
        uses: ./
        with:
          command: version
          options: --client

      - name: Check install - should not re-download
        uses: ./

  with-auth:
    name: Download with auth
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Show version
        uses: ./
        env:
          # Only required for first step in workflow where API is called
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: version
          options: --client

      - name: Check install - should not re-download
        uses: ./

      - name: This should work too
        run: |
          argocd version --client

  set-version:
    name: Set version
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Show version
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 2.4.18
          command: version
          options: --client
